b2t/grails-app/domain/b2t/Article.groovy
package b2t

class Article {

    String article_id
    String product_id
    String product_group

    String passform
    String farbfamilie
    String produkttyp
    String muster
    String groesse
    String material
    String dehnbarkeit
    String bundverarbeitung
    String transparenz
    String pflegehinweise
    String zielgruppe
    String laenge
    String gesamtlaenge_ca
    String materialhinweis
    String gefuettert
    String materialeigenschaften
    String saum
    String farbbezeichnung
    String leibhoehe
    String stil

    String attribute_text
    String marketing_text
    String top
    String bottom
    String left
    String right

    String useImage2


    static constraints = {
        article_id nullable: false, size: 6..10
        attribute_text type: "text", widget: "textArea"
        marketing_text type: "text", widget: "textArea"
    }

    String toString() {
        "$article_id"
    }
}

b2t/grails-app/controllers/b2t/ArticleController.groovy
package b2t

import grails.converters.JSON
import grails.validation.ValidationException
import grails.plugins.rest.client.RestBuilder
import groovy.json.JsonOutput
import groovy.json.JsonSlurper

import static org.springframework.http.HttpStatus.*

class ArticleController {

    ArticleService articleService
    MarketingTextService marketingTextService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def generateAttributeText = {
        def articleId = params.articleId
        def article = Article.findByArticle_id(articleId)

        def result = callAzure()

        marketingTextService.generateMarketingTextForJson(result.body)

        article.attribute_text = marketingTextService.getAttributes().toString()
        articleService.save(article)
        redirect article
    }

    def generateMarketingText = {
        def articleId = params.articleId
        def article = Article.findByArticle_id(articleId)

        def result = callAzure()

        def marketingText =  marketingTextService.generateMarketingTextForJson(result.body)
        article.marketing_text = marketingText
        articleService.save(article)

        def resultObject = new JsonSlurper().parseText(result.body)
        //render resultObject as JSON
        redirect article
    }

    def generateSmallImage = {

        def articleId = params.articleId
        def article = Article.findByArticle_id(articleId)

        if ("999999".equals(articleId)){
            article.useImage2 = "true"
            articleService.save(article)
        }
        else {
            def result = detect()

            def objects = new JsonSlurper().parseText(result.body).objects
            if (objects != null) {
                def rect = new JsonSlurper().parseText(result.body).objects.rectangle
                if (rect) {
                    article.top = rect.y.get(0)
                    article.bottom = rect.y.get(0) + rect.h.get(0)
                    article.left = rect.x.get(0)
                    article.right = rect.x.get(0) + rect.w.get(0)
                    articleService.save(article)
                }
            }
        }
        //render resultObject as JSON
        //redirect article, params: [rect: resultObject]
        //style="position:absolute;clip:rect(${this.rect.y}px,${this.rect.y+rect.h}px,${this.rect.x+rect.w}px,${this.rect.x}px)"/>
        redirect article
    }

    def callAzure() {
        RestBuilder rest = new RestBuilder()
        String articleId = params.articleId
        String url = "https://westeurope.api.cognitive.microsoft.com/vision/v2.0/analyze?visualFeatures=Brands,Categories,Color,Description,ImageType,Objects,Tags"
        def image = new File(System.properties["user.dir"] + "/grails-app/assets/images/article/woman_sweater/" + articleId + "_free_standing.png").bytes
        return rest.post(url) {
            header 'Ocp-Apim-Subscription-Key', '0f997568fa7f43b387d18a4140461f7b'
            contentType "multipart/form-data"
            accept("application/json")
            setProperty "file", image
        }
    }

    def detect() {
        RestBuilder rest = new RestBuilder()
        String articleId = params.articleId
        String url = "https://westeurope.api.cognitive.microsoft.com/vision/v2.0/detect"
        def image = new File(System.properties["user.dir"] + "/grails-app/assets/images/article/woman_sweater/" + articleId + "_free_standing.png").bytes
        return rest.post(url) {
            header 'Ocp-Apim-Subscription-Key', '0f997568fa7f43b387d18a4140461f7b'
            contentType "multipart/form-data"
            accept("application/json")
            setProperty "file", image
        }
    }

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond articleService.list(params), model:[articleCount: articleService.count()]
    }

    def show(Long id) {
        respond articleService.get(id)
    }

    def shopdetail(Long id) {
        respond articleService.get(id)
    }

    def shoplist(Long id) {
        respond articleService.get(id)
    }

    def create() {
        respond new Article(params)
    }

    def save(Article article) {
        if (article == null) {
            notFound()
            return
        }

        try {
            articleService.save(article)
        } catch (ValidationException e) {
            respond article.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'article.label', default: 'Article'), article.id])
                redirect article
            }
            '*' { respond article, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond articleService.get(id)
    }

    def update(Article article) {
        if (article == null) {
            notFound()
            return
        }

        try {
            articleService.save(article)
        } catch (ValidationException e) {
            respond article.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'article.label', default: 'Article'), article.id])
                redirect article
            }
            '*'{ respond article, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        articleService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'article.label', default: 'Article'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'article.label', default: 'Article'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

b2t/grails-app/controllers/b2t/UrlMappings.groovy
package b2t

class UrlMappings {

    static mappings = {
        "/$controller/$action?/$id?(.$format)?"{
            constraints {
                // apply constraints here
            }
        }

        "/"(controller: "article")
        "500"(view:'/error')
        "404"(view:'/notFound')
    }
}

b2t/grails-app/views/article/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'article.label', default: 'Article')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-article" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-article" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.article}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.article}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.article}" method="POST">
                <fieldset class="form">
                    <f:all bean="article"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

b2t/grails-app/views/article/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'article.label', default: 'Article')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-article" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-article" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.article}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.article}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.article}" method="PUT">
                <g:hiddenField name="version" value="${this.article?.version}" />
                <fieldset class="form">
                    <f:all bean="article"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

b2t/grails-app/views/article/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'article.label', default: 'Article')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>

    <p>&nbsp;</p>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-article" class="content scaffold-list" role="main">

            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${articleList}" maxProperties="8" properties="article_id, product_id, farbfamilie, muster, passform, material, stil"/>

            <div class="pagination">
                <g:paginate total="${articleCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

b2t/grails-app/views/article/shopdetail.gsp
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="layout" content="shopdetail" />
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Fashion Meet AI</title>


</head>

<body>

<section class="single_product_details_area d-flex align-items-center">

    <!-- Single Product Thumb -->
    <div class="single_product_thumb clearfix">
        <div class="product_thumbnail_slides owl-carousel">
            <div style="padding-left: 200px;">
                <asset:image src="article/woman_sweater/${this.article.article_id}_free_standing.png" style="width: 320px"/>
            </div>
        </div>
    </div>

    <!-- Single Product Description -->
    <div class="single_product_desc clearfix">
        <span>mango</span>
        <a href="cart.html">
            <h2>One Shoulder Glitter Midi Dress</h2>
        </a>
        <p class="product-price"><span class="old-price">$65.00</span> $49.00</p>
        <p class="product-desc">
            ${article.marketing_text}
        </p>

        <!-- Form -->
        <form class="cart-form clearfix" method="post">
            <!-- Select Box -->
            <div class="select-box d-flex mt-50 mb-30">
                <select name="select" id="productSize" class="mr-5">
                    <option value="value">Size: XL</option>
                    <option value="value">Size: X</option>
                    <option value="value">Size: M</option>
                    <option value="value">Size: S</option>
                </select>
                <select name="select" id="productColor">
                    <option value="value">Color: Black</option>
                    <option value="value">Color: White</option>
                    <option value="value">Color: Red</option>
                    <option value="value">Color: Purple</option>
                </select>
            </div>
            <!-- Cart & Favourite Box -->
            <div class="cart-fav-box d-flex align-items-center">
                <!-- Cart -->
                <button type="submit" name="addtocart" value="5" class="btn essence-btn">Add to cart</button>
                <!-- Favourite -->
                <div class="product-favourite ml-4">
                    <a href="#" class="favme fa fa-heart"></a>
                </div>
            </div>
        </form>
    </div>
</section>

</body>

</html>

b2t/grails-app/views/article/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'article.label', default: 'Article')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>

        <a href="#show-article" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><g:link class="list" action="index">Artikel Übersicht</g:link></li>
                <li><g:link class="create" action="create">Artikel anlegen</g:link></li>
            </ul>
        </div>
        <div id="show-article" class="content scaffold-show" role="main">
            <h1>Artikel anzeigen</h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>

            <ol class="property-list article">
                <li class="fieldcontain">
                    <span id="article_id-label" class="property-label">&nbsp;</span>
                    <div class="property-value" aria-labelledby="article_id-label">
                        <g:if test="${!('999999'.equals(this.article.article_id)) || this.article.useImage2}">
                            <asset:image height="300px" src="article/woman_sweater/${this.article.article_id}_free_standing.png"/>
                        </g:if>
                        <g:else>
                            <asset:image height="300px" src="article/woman_sweater/${this.article.article_id}handy_free_standing.png"/>
                        </g:else>
                        <g:if test="${this.article.top}">
                            <asset:image height="300px;" src="article/woman_sweater/${this.article.article_id}_free_standing.png"
                                         style="position:absolute;clip:rect(${this.article.top}px,${this.article.right}px,${this.article.bottom}px,${this.article.left}px)"/>
                        </g:if>
                        <br>
                        <g:link class="edit" action="generateSmallImage" params="[articleId: this.article.article_id]">Bild optimieren</g:link>
                        <br>
                        <g:link class="edit" action="generateAttributeText" params="[articleId: this.article.article_id]">Attribute generieren</g:link>
                        <br>
                        <g:link class="edit" action="generateMarketingText" params="[articleId: this.article.article_id]">Marketingtexte generieren</g:link>
                        <br>
                        <g:link class="edit" action="shopdetail" params="[articleId: this.article.article_id, id:article.id]">Im Shop anzeigen</g:link>
                    </div>
                </li>
            </ol>

            <g:if test="${false}">
            <div>
                <pre>
                    ${article.attribute_text}
                </pre>
            </div>
            </g:if>

            <f:display bean="article" />

            <g:form resource="${this.article}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.article}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

b2t/grails-app/views/image/upload.gsp
<%@ page contentType="text/html;charset=UTF-8" %>
<html>
<head>
  <title>Image Upload</title>
</head>
<body>

</body>
</html>

b2t/grails-app/views/layouts/main.gsp
<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>
        <g:layoutTitle default="Grails"/>
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <asset:link rel="icon" href="favicon.ico" type="image/x-ico"/>

    <asset:stylesheet src="application.css"/>

    <g:layoutHead/>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-dark navbar-static-top" role="navigation">
    <a class="navbar-brand" href="/#"><asset:image src="logo_fashion_ai.png" height="70px"/></a>
    <h1 style="font-size: 42px; font-weight: bold; vertical-align: middle" class="pl-6 text-white text-center text-lg-center">
        &nbsp;&nbsp;&nbsp;AI -> Produktbilder -> Attribute -> Marketingtexte</h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
        &nbsp;<span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" aria-expanded="false" style="height: 0.8px;" id="navbarContent">
        <ul class="nav navbar-nav ml-auto">
            <g:pageProperty name="page.nav"/>
        </ul>
    </div>

</nav>

<g:layoutBody/>



<div id="spinner" class="spinner" style="display:none;">
    <g:message code="spinner.alt" default="Loading&hellip;"/>
</div>

<asset:javascript src="application.js"/>

</body>
</html>